### PR TITLE
Reduce logging level (#16)

### PR DESCRIPTION
**Pull request by besbes**

### CODE REVIEW

**Comment by cljk** [comment]
please merge this PR

**Comment by besbes** [comment]
@cljk As I do not have write access to this repo, I cannot merge.

**Comment by cljk** [comment]
I know that ;-)
That was dedicated to the maintainers

**Comment by basiliscus** [comment]
Hi @besbes , @cljk 

You can easily suppress the messages by modifying the `logging.properties` file in your project. Just add the following line to the very end:

com.ecwid.maleorang.level=WARNING

**Comment by besbes** [comment]
@basiliscus I am aware of that, however I think that a log level of `INFO` is inappropriate for a (very verbose) full request/response content dump. The [Javadoc](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html#INFO) says: "[...] the INFO level should only be used for reasonably significant messages that will make sense to end users and system administrators" - of course personal taste but I think full request/response dumps are not "reasonably significant".

**Comment by cljk** [comment]
I share the argument of @besbes - also the communication data might contain sensitive data (personal data) and should not be logged by default.

**Pull request merged**
